import { WeaponSkin } from '../types';
export type { WeaponSkin };

export const WEAPON_SKINS_CATALOG: WeaponSkin[] = [
  {
    id: 'skin_default',
    name: 'Katana Cyan Standard',
    subtitle: 'Modèle de dotation des hacktivistes de Montréal',
    description: 'Lame d’énergie cybernétique standard émettant un faisceau de plasma cyan cohérent et stable.',
    rarity: 'standard',
    bladeStyle: 'katana',
    bladeColor: '#00f3ff',
    secondaryColor: '#ffffff',
    trailColor: '#00f3ff',
    particleType: 'plasma',
    glowIntensity: 18,
    icon: 'Sword',
    unlockCondition: 'Disponible par défaut au début de l’incursion.',
    unlockType: 'default'
  },
  {
    id: 'skin_matrix_glitch',
    name: 'Lame Binaire Glitch Matrix',
    subtitle: 'Lame gravée d’algorithmes décompilés',
    description: 'Une lame holographique verte traversée de cascades perpétuelles de glyphes binaires et de bugs de rendu visuel.',
    rarity: 'rare',
    bladeStyle: 'matrix_glitch',
    bladeColor: '#00ff41',
    secondaryColor: '#ffffff',
    trailColor: '#00ff41',
    particleType: 'glitch',
    glowIntensity: 22,
    icon: 'Terminal',
    unlockCondition: 'Débloqué via les compétences ou le Codex.',
    unlockType: 'achievement'
  },
  {
    id: 'skin_solar_flare',
    name: 'Épée Solaire Thermite',
    subtitle: 'Lame à induction thermique 3000°C',
    description: 'Forgée dans du titane liquide surchauffé, cette épée projette une traînée de flammes solaires dorées et d’étincelles de fusion.',
    rarity: 'rare',
    bladeStyle: 'solar_flare',
    bladeColor: '#f2994a',
    secondaryColor: '#ffdd00',
    trailColor: '#f2994a',
    particleType: 'fire',
    glowIntensity: 25,
    icon: 'Flame',
    unlockCondition: 'Atteindre le Stage 2 ou vaincre un Boss en Tier élevé.',
    unlockType: 'stage_clear'
  },
  {
    id: 'skin_hyper_crimson',
    name: 'Muramasa Hyper-Crimson',
    subtitle: 'Lame d’assassinat haute fréquence',
    description: 'Une longue lame d’énergie rouge sang pulsant d’arcs électriques violents, conçue pour les frappes chirurgicales dévastatrices.',
    rarity: 'epic',
    bladeStyle: 'plasma_cleaver',
    bladeColor: '#ff0044',
    secondaryColor: '#ff7799',
    trailColor: '#ff0044',
    particleType: 'sparks',
    glowIntensity: 26,
    icon: 'Zap',
    unlockCondition: 'Réaliser 100 éliminations ou un combo critique de 25+.',
    unlockType: 'achievement'
  },
  {
    id: 'skin_cryo_saber',
    name: 'Sabre Cryo-Zéro Absolu',
    subtitle: 'Refroidisseur supraconducteur quantique',
    description: 'Une lame formée de cristaux de glace subatomiques et de brume cryogénique d’un bleu polaire étincelant.',
    rarity: 'epic',
    bladeStyle: 'cryo_saber',
    bladeColor: '#38bdf8',
    secondaryColor: '#e0f2fe',
    trailColor: '#7dd3fc',
    particleType: 'frost',
    glowIntensity: 24,
    icon: 'Sparkles',
    unlockCondition: 'Achetable auprès du Marchand Nomade (Wandering Trader) pour 1 200 Nanites.',
    unlockType: 'trader',
    priceNanites: 1200
  },
  {
    id: 'skin_thunder_arc',
    name: 'Lame Foudre Synaptique',
    subtitle: 'Canalisateur d’influx nerveux mégavolt',
    description: 'Des arcs de haute tension électrique crépitent le long de cette lame d’énergie psionique bleue et violette.',
    rarity: 'epic',
    bladeStyle: 'thunder_arc',
    bladeColor: '#818cf8',
    secondaryColor: '#c084fc',
    trailColor: '#818cf8',
    particleType: 'thunder',
    glowIntensity: 28,
    icon: 'Zap',
    unlockCondition: 'Débloquer une compétence ultime dans l’arbre des compétences.',
    unlockType: 'achievement'
  },
  {
    id: 'skin_void_reaper',
    name: 'Faucheuse du Néant Quantique',
    subtitle: 'Singularité gravitationnelle forgée',
    description: 'Une lourde lame en matière noire violette absorbant la lumière ambiante et semant des micro-constellations stellaires dans son sillage.',
    rarity: 'legendary',
    bladeStyle: 'void_reaper',
    bladeColor: '#a855f7',
    secondaryColor: '#ec4899',
    trailColor: '#9333ea',
    particleType: 'void',
    glowIntensity: 30,
    icon: 'Crosshair',
    unlockCondition: 'Atteindre ou triompher du Stage 4 (La Citadelle Orbitale).',
    unlockType: 'stage_clear'
  },
  {
    id: 'skin_obsidian_stealth',
    name: 'Dague d’Obsidienne Stealth',
    subtitle: 'Technologie d’absorption radar nanométrique',
    description: 'Lame d’un noir d’ébène mat avec des lisérés d’or pur et un halo de fumée d’ombre furtive.',
    rarity: 'epic',
    bladeStyle: 'obsidian_stealth',
    bladeColor: '#1e293b',
    secondaryColor: '#f59e0b',
    trailColor: '#334155',
    particleType: 'sparks',
    glowIntensity: 16,
    icon: 'Shield',
    unlockCondition: 'Achetable auprès du Marchand Nomade pour 1 500 Nanites.',
    unlockType: 'trader',
    priceNanites: 1500
  },
  {
    id: 'skin_prismatic_god',
    name: 'Overclock Prismatique Chroma God',
    subtitle: 'Synthèse parfaite de photons purs',
    description: 'Le chef-d’œuvre ultime de la Cyber-Forge : une lame arc-en-ciel chromatique dont les spectres de lumière s’entremêlent en vagues prismatiques.',
    rarity: 'legendary',
    bladeStyle: 'prismatic_god',
    bladeColor: '#ff00ff',
    secondaryColor: '#00f3ff',
    trailColor: '#f59e0b',
    particleType: 'rainbow',
    glowIntensity: 35,
    icon: 'Award',
    unlockCondition: 'Effectuer 3 fusions d’implants dans la Cyber-Forge.',
    unlockType: 'forge'
  }
];

export function getWeaponSkinById(skinId?: string): WeaponSkin {
  const found = WEAPON_SKINS_CATALOG.find((s) => s.id === skinId);
  return found || WEAPON_SKINS_CATALOG[0];
}
